### ISSUE TITLE
Ruler isn't updating when zooming in or out

### ISSUE THREAD

**Issue by laurensvane** [vinsworldcom/nppColumnTools#8]
When i zoom the notepad++ view with ctrl + + or ctrl + - the ruler isn't resizing with the zoom level.
When i disable and enable the ruler it's fixed, but it would be nice if it auto updates.

**Comment by vinsworldcom** [comment]
Have a look at [1.4.2.1 pre-release](https://github.com/vinsworldcom/nppColumnTools/releases/tag/1.4.2.1)

**Comment by vinsworldcom** [comment]
Seem using the "Restore Default Zoom" still doesn't work.  N++ code uses [SCI_SETZOOM](https://www.scintilla.org/ScintillaDoc.html#SCI_SETZOOM)(0) to facilitate this:

notepad-plus-plus\PowerEditor\src\NppCommands.cpp:
```C++
2172: 		case IDM_VIEW_ZOOMRESTORE:
2173: 			//Zoom factor of 0 points means default view
2174: 			_pEditView->execute(SCI_SETZOOM, 0);//_zoomOriginalValue);
2175: 			break;
```

Which according to [SCN_ZOOM](https://www.scintilla.org/ScintillaDoc.html#SCN_ZOOM) should trigger.  Seems to not be happening.  Using an additional `case SCN_PAINTED` fixes, but also add flicker since this event triggers ***WAY*** more often.
